### PR TITLE
Migrate to bem-xjst 8.8.4

### PR DESCRIPTION
**Pull request by miripiruni**
Instead of https://github.com/enb/enb-bemxjst/pull/280

cc @dustyo-O (sorry, I can’t push to your fork ;)

cc @tadatuta

### CODE REVIEW

**Comment by tadatuta** [comment]
this part looks good to me but I think we can't release it until all the issues with export will be fixed

**Comment by miripiruni** [comment]
bem-xjst@8.8.3 is out.

**Comment by miripiruni** [comment]
Updated.

**Comment by miripiruni** [comment]
@tadatuta can you take a look at it please?

**Comment by dustyo-O** [comment]
@miripiruni 
i want to add several tests for this pull request, how to do it? 3 bemhtml test, to cover correct module require

**Comment by zxqfox** [comment]
@dustyo-O Accept the invite here https://github.com/enb/enb-bemxjst/invitations, run `git remote rename origin mine; git remote set-url origin git@github.com:enb/enb-bemxjst.git`, fetch and checkout @miripiruni's branch `migrate-to-8.8.2`, add your tests as separate commit, and push it to origin. PROFIT!

**Comment by miripiruni** [comment]
@dustyo-O tests failed.

**Comment by dustyo-O** [comment]
works like charm locally, managing things out

**Comment by dustyo-O** [comment]
hmph, tests ok, whats wrong with coverage?

**Comment by zxqfox** [comment]
@tadatuta @dustyo-O Yey?! Or something else needed?

**Comment by dustyo-O** [comment]
we still have issue when we trying to require from global and commonJS - global var will overwrite the one imported from commonJS - we have to make significant refactor in enb-xjst to resolve such cases in tree, making the best choise individually for each module.

i propose to solve this in next version

**Comment by dustyo-O** [comment]
everything is ok to me here

**Comment by zxqfox** [comment]
@blond Let's merge?

**Comment by miripiruni** [comment]
@tadatuta updated (migrate to v8.8.4)

**Comment by tadatuta** [comment]
lgtm, let's merge!

**Comment by miripiruni** [comment]
OK, let’s publish enb-bemxjst 8.8.4

**Pull request merged**
